name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a animação da cobra
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Enviar os arquivos gerados para o repositório
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
